#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name:  MELANY MERO PILLASAGUA 

# Short bio or description (displayed in the header)
description:  BIENVENIDOS A MI BLOG 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email:   [melanymero7@gmail.com]
  facebook:   [https://www.facebook.com/melany.mero.9]
  instagram:    [https://www.instagram.com/melany14.mero/?hl=es-la]
  rss:  Androip
  twitter:   [https://twitter.com/15Melanymero]
  




permalink:  BLOG PERSONAL 

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-midnight
